_target_: diffusion_policy.model.flow_matching.flow_matching_git.FlowMatchingInvariantPointTransformer
obs_dim: ${embedding_dim}
n_action_steps: ${n_action_steps}
gripper_out: true
ignore_collisions_out: true
latent_dim: 128
depth: 4
heads: 3
dim_head: 60
dropout: 0.05
n_obs_steps: ${n_obs_steps}
