name: se3diffuser
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - dglteam/label/th23_cu121
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch3d
  - pytorch-cuda=12.1
  - dgl
  - wandb
  - matplotlib
  - click
  - hydra-core
  - dill
  - tqdm
  - wandb
  - diffusers
  - pip:
    - pydantic
    - pandas
    - torchdata 
    - numpy==1.26.4
    - moviepy 
    - imageio 
    - matplotlib==3.6.1
    - tabulate
    - einops
    - zarr
    - dill
    - numcodecs
    - typed-argument-parser
    - absl-py
    - pillow
    - plotly
    - packaging
    - ninja 
    - git+https://github.com/openai/CLIP.git

