
cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/baseline_image
sbatch train_open_drawer_image.sh 
sbatch train_put_item_in_drawer_image.sh
sbatch train_stack_blocks_image.sh
sbatch train_sweep_to_dustpan_of_size_image.sh
sbatch train_turn_tap_image.sh

cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/baseline_lowdim
sbatch train_open_drawer_lowdim.sh
sbatch train_put_item_in_drawer_lowdim.sh
sbatch train_stack_blocks_lowdim.sh
sbatch train_sweep_to_dustpan_of_size_lowdim.sh
sbatch train_turn_tap_lowdim.sh
  
cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/baseline_mask
sbatch train_open_drawer_mask.sh
sbatch train_put_item_in_drawer_mask.sh
sbatch train_stack_blocks_mask.sh
sbatch train_sweep_to_dustpan_of_size_mask.sh
sbatch train_turn_tap_mask.sh

cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/pose_invariant_image
sbatch train_open_drawer_image_v2.sh
sbatch train_put_item_in_drawer_image_v2.sh
sbatch train_stack_blocks_image_v2.sh
sbatch train_sweep_to_dustpan_of_size_image_v2.sh
sbatch train_turn_tap_image_v2.sh

cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/pose_invariant_lowdim
sbatch train_open_drawer_lowdim.sh
sbatch train_put_item_in_drawer_lowdim.sh
sbatch train_stack_blocks_lowdim.sh
sbatch train_sweep_to_dustpan_of_size_lowdim.sh
sbatch train_turn_tap_image_lowdim.sh

cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/pose_invariant_lowdim_v2
sbatch train_open_drawer_lowdim_v2.sh
sbatch train_put_item_in_drawer_lowdim_v2.sh
sbatch train_stack_blocks_lowdim_v2.sh
sbatch train_sweep_to_dustpan_of_size_lowdim_v2.sh
sbatch train_turn_tap_image_lowdim_v2.sh

cd ${DIFFUSION_POLICY_ROOT}/slurm_scripts/pose_invariant_mask
sbatch train_open_drawer_mask_v2.sh
sbatch train_put_item_in_drawer_mask_v2.sh
sbatch train_stack_blocks_mask_v2.sh
sbatch train_sweep_to_dustpan_of_size_mask_v2.sh
sbatch train_turn_tap_mask_v2.sh