# Actually the task entry loads the yaml file inside task
name: eval_se3_flow_matching
model_to_eval_path: /home/funk/Code_TUD/3d_repr_learning/diffusion_policy/data/outputs/cluster_trains_12_01/img_rescale0/00.03.52_train_se3_flow_matching_fms1_open_drawer_image
epochs_to_eval: [2000,5000,9000]
n_vis: 0 # max set to 1 but maybe set to 0 for no visualization
n_procs_max: 5 #typically set to 5

logging:
  project: point_attention_debug_eval
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}
  id: null
  group: null
  tags: ["${name}"]

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
    subdir: ${hydra.job.num}
