datatype: image
instructions: ${oc.env:DIFFUSION_POLICY_ROOT}/data/rlbench_instructions/instructions.pkl
tasks:
  - open_drawer
  - sweep_to_dustpan_of_size
variations: 
  - 0
  - 1
  - 3

task_desc: ${eval:'${tasks}[0] if len(${tasks}) == 1 else "multi_task"'}

gripper_loc_bounds: 
  _target_: diffusion_policy.common.rlbench_util.get_gripper_loc_bounds
  path: "${oc.env:DIFFUSION_POLICY_ROOT}/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0

workspace_bounds:
  _target_: diffusion_policy.common.rlbench_util.get_workspace_bounds
  path: "${oc.env:DIFFUSION_POLICY_ROOT}/diffusion_policy/tasks/peract_workspace_bounds.json"
  buffer: 0.0

cameras: ['left_shoulder', 'right_shoulder', 'wrist', 'front']
use_lowdim_pcd: False

dataset:
  _target_: diffusion_policy.dataset.rlbench_dataset.RLBenchDataset
  root: ${oc.env:DIFFUSION_POLICY_ROOT}/data/peract.zarr
  n_episodes: ${num_episodes}
  cameras: ${cameras}
  n_obs_steps: ${n_obs_steps}
  use_mask: False
  use_lowdim_pcd: ${use_lowdim_pcd}
  cache_size: 2000
  image_rescale: [1., 1.]
  rot_noise_scale: 0.0
  pos_noise_scale: 0.0
  use_precomputed_features: False
  feature_res: "res2"

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_runner.RLBenchRunner
  data_root: ""
  max_episodes: 25
  max_rrt_tries: 1
  demo_tries: 1
  n_train_vis: 1
  n_val_vis: 1
  n_procs_max: 5
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  obs_history_from_planner: False
  obs_history_augmentation_every_n: None
  collision_checking: True
  action_dim: 8
  headless: True
  apply_rgb: True
  apply_cameras: ${cameras}
  apply_pc: True
  apply_mask: False
  apply_low_dim_pcd: ${use_lowdim_pcd}
  apply_pose: false
