defaults:
  - _self_
  - task: pusht_image

task_name: ${task.name}
shape_meta: ${task.shape_meta}

name: multi_image_and_position_obs_encoder
horizon: 16
n_obs_steps: 2
n_action_steps: 8
past_action_visible: False


obs_encoder:
  _target_: diffusion_policy.model.vision.multi_image_and_position_obs_encoder.MultiImageAndPositionObsEncoder

  shape_meta: ${shape_meta}

  rgb_model:
    _target_: diffusion_policy.model.vision.model_getter.get_resnet
    name: resnet18
    weights: IMAGENET1K_V1 # or r3m
    
  resize_shape: [256, 256]
  crop_shape: [224, 224]
  random_crop: False
  use_group_norm: False
  share_rgb_model: True
  imagenet_norm: True


hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
