defaults:
  - _self_
  - task: open_drawer_lowdim

name: diffusion_unet_lowdim_relative_policy
_target_: diffusion_policy.workspace.diffusion_unet_lowdim_relative_policy.DiffusionUnetLowDimRelativePolicy

checkpoint:
  topk:
    monitor_key: train_loss
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

dataloader:
  batch_size: 1024
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 1024
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: True

#dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0

task_name: ${task.name}
exp_name: "default"
horizon: 1
n_obs_steps: &n_obs_steps 2
n_action_steps: 1
embedding_dim: 60

optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06

policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_relative_policy.DiffusionUnetLowDimRelativePolicy
     
  shape_meta: ${task.shape_meta}

  obs_encoder:
    _target_: diffusion_policy.model.vision.transformer_lowdim_obs_relative_encoder.TransformerHybridObsRelativeEncoder
    shape_meta: ${task.shape_meta}
    n_obs_steps: ${n_obs_steps}
    query_embeddings: 
      _target_: torch.nn.Embedding
      num_embeddings: ${n_obs_steps}
      embedding_dim: ${embedding_dim}
    keypoint_embeddings: 
      _target_: torch.nn.Embedding
      num_embeddings: ${task.num_keypoints}
      embedding_dim: ${embedding_dim}
    rotary_embedder: 
      _target_: diffusion_policy.model.common.position_encodings.RotaryPositionEncoding2D
      feature_dim: ${embedding_dim}
    positional_embedder:
      _target_: diffusion_policy.model.common.position_encodings.SinusoidalPosEmb
      dim: ${embedding_dim}
    within_attn: 
      _target_: diffusion_policy.model.common.layer.RelativeCrossAttentionModule
      embedding_dim: ${embedding_dim}
      num_attn_heads: 5
      num_layers: 5
    across_attn: 
      _target_: diffusion_policy.model.common.layer.RelativeCrossAttentionModule
      embedding_dim: ${embedding_dim}
      num_attn_heads: 5
      num_layers: 5

  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  gripper_loc_bounds: ${task.gripper_loc_bounds}
  relative_trajectory: True
    

training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 100000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1

logging:
  project: diffusion_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  id: null
  group: null
  tags: ["${name}", "${task_name}", "${exp_name}"]

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
