name: open_drawer_image

shape_meta: &shape_meta 
  obs:
    rgb:
      shape: [3, 128, 128]
      type: rgb
    agent_pose:
      shape: [4,4]
      type: low_dim
    pcd:
      shape: [3, 128, 128]
      type: pcd
  action:
    shape: [4,4]


gripper_loc_bounds: 
  _target_: diffusion_policy.common.common_utils.get_gripper_loc_bounds
  path: "/home/felix/Workspace/diffusion_policy_felix/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0
  task: ${name}

# cameras: ['left_shoulder', 'right_shoulder', 'wrist', 'front']
cameras: ['wrist', 'front']

dataset:
  _target_: diffusion_policy.dataset.rlbench_dataset.RLBenchDataset
  root: /home/felix/Workspace/diffusion_policy_felix/data/peract
  task_name: open_drawer
  cameras: ${task.cameras}
  num_episodes: ${num_episodes}
  variation: 0
  demo_augmentation_every_n: 1
  n_obs_steps: ${n_obs_steps}
  val_ratio: 0.2
  use_pcd: true
  use_rgb: true

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_runner.RLBenchRunner
  data_root: ${task.dataset.root}
  task_str: "open_drawer"
  max_episodes: 3
  max_steps: ${eval:'20 if "${use_keyframe_actions}" else 200'}
  max_rtt_tries: 1
  demo_tries: 1
  n_train_vis: 3
  n_val_vis: 3
  n_obs_steps: ${n_obs_steps}
  obs_history_augmentation_every_n: ${task.dataset.obs_augmentation_every_n}
  collision_checking: True
  action_dim: 8
  headless: True
  apply_low_dim_pcd: true
  apply_pose: true
  adaptor:
    _target_: diffusion_policy.common.adaptors.Peract2Robomimic