name: open_drawer

num_keypoints: &num_keypoints 21
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agent_pose:
      shape: [4,4]
      type: low_dim
    keypoint_pcd:
      shape: [*num_keypoints, 3]
      type: low_dim
    keypoint_idx:
      shape: [*num_keypoints]
      type: low_dim
  action:
    shape: [4,4]

gripper_loc_bounds: 
  _target_: diffusion_policy.common.common_utils.get_gripper_loc_bounds
  path: "/home/felix/Workspace/diffusion_policy_felix/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0
  task: ${name}

dataset:
  _target_: diffusion_policy.dataset.rlbench_dataset.RLBenchDataset
  root: /home/felix/Workspace/diffusion_policy_felix/data/train
  task_name: open_drawer
  cameras: []
  num_episodes: 1
  variation: 0
  demo_augmentation_every_n: 1
  n_obs: ${n_obs_steps}
  build_history_from_augment_obs: True
  keypoints_only: True
  val_ratio: 0.2

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_lowdim_runner.RLBenchLowdimRunner
  data_root: ${task.dataset.root}
  task_str: "open_drawer"
  max_episodes: 5
  max_steps: 3
  max_rtt_tries: 10
  demo_tries: 5
  obs_history_augmentation_every_n: 1
  collision_checking: True
  action_dim: 8
  headless: True
