name: open_drawer

#
observation_type: low_dim
num_objects: 5
num_keypoints: ${eval:'${task.num_objects} * 7'}

shape_meta: &shape_meta 
  obs:
    agent_pose:
      shape: [4,4]
      type: low_dim
    low_dim_pcd:
      shape: 
        - ${task.num_keypoints}
        - 3
      type: low_dim
    keypoint_poses:
      shape: 
        - ${task.num_objects}
        - 4
        - 4
      type: low_dim
    low_dim_state:
      shape: 
        - ${n_obs_steps}
        - 3
      type: low_dim
  action:
    shape: [4,4]

gripper_loc_bounds: 
  _target_: diffusion_policy.common.common_utils.get_gripper_loc_bounds
  path: "/home/felix/Workspace/diffusion_policy_felix/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0
  task: ${name}

obs_augmentation_every_n: 10
obs_history_from_planner: False
use_keyframe_observations: False
dataset:
  _target_: diffusion_policy.dataset.rlbench_dataset.RLBenchDataset
  root: /home/felix/Workspace/diffusion_policy_felix/data/keypoint/train
  task_name: open_drawer_keypoint
  cameras: []
  num_episodes: ${num_episodes}
  variation: 0
  n_obs_steps: ${n_obs_steps}
  horizon: ${horizon}
  use_keyframe_actions: ${use_keyframe_actions}
  use_keyframe_observations: ${task.use_keyframe_observations}
  demo_augmentation_every_n: 1
  obs_augmentation_every_n: ${eval:'${task.obs_augmentation_every_n} if ${task.obs_history_from_planner} else ${n_action_steps}'}
  val_ratio: 0.2
  use_low_dim_pcd: true
  use_pose: true
  use_low_dim_state: true

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_runner.RLBenchRunner
  data_root: ${task.dataset.root}
  task_str: "open_drawer_keypoint"
  max_episodes: 3
  max_steps: ${eval:'20 if ${use_keyframe_actions} else 60'}
  max_rtt_tries: 10
  demo_tries: 1
  n_train_vis: 3
  n_val_vis: 3
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  obs_history_from_planner: ${task.obs_history_from_planner}
  obs_history_augmentation_every_n: ${task.dataset.obs_augmentation_every_n}
  collision_checking: True
  action_dim: 8
  headless: True
  apply_low_dim_pcd: true
  apply_pose: true
  adaptor:
    _target_: diffusion_policy.common.adaptors.Peract2Robomimic