name: open_drawer

image_size: [128, 128]

gripper_loc_bounds: 
  _target_: diffusion_policy.common.rlbench_util.get_gripper_loc_bounds
  path: "${oc.env:DIFFUSION_POLICY_ROOT}/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0
  task: ${name}

cameras: ['left_shoulder', 'right_shoulder', 'wrist', 'front']

dataset:
  _target_: diffusion_policy.dataset.rlbench_next_best_pose_dataset.RLBenchNextBestPoseDataset
  dataset_path: ${oc.env:DIFFUSION_POLICY_ROOT}/data/peract.zarr
  n_episodes: ${num_episodes}
  task_name: ${task.name}
  cameras: ${task.cameras}
  n_obs_steps: ${n_obs_steps}
  use_keypoint_obs_only: True
  val_ratio: 0.2
  use_low_dim_state: False
  use_mask: True

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_runner.RLBenchRunner
  data_root: ""
  task_str: ${task.name}
  max_episodes: 3
  max_steps: 3
  max_rrt_tries: 5
  demo_tries: 1
  n_train_vis: 3
  n_val_vis: 3
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  obs_history_from_planner: False
  obs_history_augmentation_every_n: None
  collision_checking: True
  action_dim: 8
  headless: True
  apply_rgb: True
  apply_cameras: ${task.cameras}
  apply_pc: True
  apply_mask: True
  apply_low_dim_pcd: false
  apply_pose: false
  image_size: ${task.image_size}
  adaptor:
    _target_: diffusion_policy.common.adaptors.Peract2Robomimic
