image_size: [128, 128]
type: image

gripper_loc_bounds: 
  _target_: diffusion_policy.common.rlbench_util.get_gripper_loc_bounds
  path: "${oc.env:DIFFUSION_POLICY_ROOT}/diffusion_policy/tasks/18_peract_tasks_location_bounds.json"
  buffer: 0.0
  task: ${task.task_name}

cameras: ['left_shoulder', 'right_shoulder', 'wrist', 'front']

dataset:
  _target_: diffusion_policy.dataset.rlbench_dataset.RLBenchNextBestPoseDataset
  dataset_path: ${oc.env:DIFFUSION_POLICY_ROOT}/data/image_keypoints_v3.zarr  
  n_episodes: ${num_episodes}
  task_name: ${task.task_name}
  cameras: ${task.cameras}
  n_obs_steps: ${n_obs_steps}
  val_ratio: 0.2
  use_low_dim_state: False
  use_mask: True
  cache_size: 1000
  image_rescale: [1., 1.]
  rot_noise_scale: 0.0
  pos_noise_scale: 0.0

env_runner:
  _target_: diffusion_policy.env_runner.rlbench_runner.RLBenchRunner
  data_root: ""
  task_str: ${task.task_name}
  max_episodes: 25
  max_steps: 3
  max_rrt_tries: 1
  demo_tries: 1
  n_train_vis: 1
  n_val_vis: 1
  n_procs_max: 5
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  obs_history_from_planner: False
  obs_history_augmentation_every_n: None
  collision_checking: True
  action_dim: 8
  headless: True
  apply_rgb: True
  apply_cameras: ${task.cameras}
  apply_pc: True
  apply_mask: True
  apply_low_dim_pcd: false
  apply_pose: false
  image_size: ${task.image_size}
